[package]
name = "iso-3166-2"
version = "0.1.0"
authors = ["Alex <segler_alex@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
